# documentation: https://ce.judge0.com/
# slogan: Judge0, where code happens.
# tags: code,run,compute
# logo: svgs/judge0.png
# port: 2358
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: "100M"

services:
  judge0:
    image: judge0/judge0:1.13.1
    privileged: true
    environment:
      - SERVICE_FQDN_SERVER_2358
      - REDIS_HOST=${COOLIFY_REDIS_HOST:-redis}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - POSTGRES_HOST=${COOLIFY_POSTGRES_HOST:-db}
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - AUTHZ_TOKEN=${SERVICE_PASSWORD_AUTHZ}
    healthcheck:
      test: curl -fs http://127.0.0.1:2358/workers > /dev/null
      interval: 5s
      retries: 10
    <<: *default-logging

  worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    privileged: true
    environment:
      - REDIS_HOST=${COOLIFY_REDIS_HOST:-redis}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - POSTGRES_HOST=${COOLIFY_POSTGRES_HOST:-db}
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - AUTHZ_TOKEN=${SERVICE_PASSWORD_AUTHZ}
    <<: *default-logging

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging

  redis:
    image: redis:7.2.4
    command:
      - bash
      - -c
      - docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"
    restart: always
    environment:
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    <<: *default-logging
